version: 2.1

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
      - build-test-linux

jobs:
  build-test-linux:
    docker:
      - image: circleci/python:2 # same image restwrappers use
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build -t launchdarkly-haproxy .
      - run:
          name: Run Image
          command: docker run --rm --name nginx -e LD_SDK_KEY="a" -e LD_FLAG_KEY="a" launchdarkly-haproxy
          background: true
      - run:
          name: Test Image
          command: docker run --network container:nginx appropriate/curl --retry 10 --retry-connrefused http://localhost:8123
          timeout: 300
